services:
  - type: static
    name: meditrack-client
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://meditrack-x4v3.onrender.com/api
      - key: NODE_ENV
        value: production

  - type: web
    name: meditrack-server
    env: node
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://meditrack-e.netlify.app
      - key: MONGO_URI
        value: mongodb+srv://universet560_db_user:uUe7tiCDlZFUjx7P@cluster0.rlwoqiw.mongodb.net/
      - key: JWT_SECRET
        value: supersecretjwtkey
      - key: JWT_REFRESH_SECRET
        value: supersecretrefreshkey
      - key: EMAIL_HOST
        value: smtp.ethereal.email
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: your_email_user
      - key: EMAIL_PASS
        value: your_email_pass
